// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfErNLyS_OpdTcGf9a6ugyShk0skdPjBU',
    appId: '1:573697436801:ios:7608a810cdbd61c9e43180',
    messagingSenderId: '573697436801',
    projectId: 'screenshot-gallery-e3e8d',
    storageBucket: 'screenshot-gallery-e3e8d.firebasestorage.app',
    iosBundleId: 'com.example.screenshotGallery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfErNLyS_OpdTcGf9a6ugyShk0skdPjBU',
    appId: '1:573697436801:ios:7608a810cdbd61c9e43180',
    messagingSenderId: '573697436801',
    projectId: 'screenshot-gallery-e3e8d',
    storageBucket: 'screenshot-gallery-e3e8d.firebasestorage.app',
    iosBundleId: 'com.example.screenshotGallery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB96Bgpm66zTXEWofKCK9YFUfjjyll2ASY',
    appId: '1:573697436801:web:0f54e319c021ea34e43180',
    messagingSenderId: '573697436801',
    projectId: 'screenshot-gallery-e3e8d',
    authDomain: 'screenshot-gallery-e3e8d.firebaseapp.com',
    storageBucket: 'screenshot-gallery-e3e8d.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB96Bgpm66zTXEWofKCK9YFUfjjyll2ASY',
    appId: '1:573697436801:web:0f54e319c021ea34e43180',
    messagingSenderId: '573697436801',
    projectId: 'screenshot-gallery-e3e8d',
    authDomain: 'screenshot-gallery-e3e8d.firebaseapp.com',
    storageBucket: 'screenshot-gallery-e3e8d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqfiIZqDkfD0UJK0xNoWY8ZAGZnytyE14',
    appId: '1:573697436801:android:2b5c073e1edb390ee43180',
    messagingSenderId: '573697436801',
    projectId: 'screenshot-gallery-e3e8d',
    storageBucket: 'screenshot-gallery-e3e8d.firebasestorage.app',
  );
}
